# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alialboainin96/project/MouseEditor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alialboainin96/project/MouseEditor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alialboainin96/project/MouseEditor/CMakeFiles /home/alialboainin96/project/MouseEditor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alialboainin96/project/MouseEditor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mouse

# Build rule for target.
mouse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mouse
.PHONY : mouse

# fast build rule for target.
mouse/fast:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/build
.PHONY : mouse/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) -f vendor/spdlog/CMakeFiles/spdlog.dir/build.make vendor/spdlog/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

src/log/log.o: src/log/log.cpp.o

.PHONY : src/log/log.o

# target to build an object file
src/log/log.cpp.o:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/log/log.cpp.o
.PHONY : src/log/log.cpp.o

src/log/log.i: src/log/log.cpp.i

.PHONY : src/log/log.i

# target to preprocess a source file
src/log/log.cpp.i:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/log/log.cpp.i
.PHONY : src/log/log.cpp.i

src/log/log.s: src/log/log.cpp.s

.PHONY : src/log/log.s

# target to generate assembly for a file
src/log/log.cpp.s:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/log/log.cpp.s
.PHONY : src/log/log.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ui/file.o: src/ui/file.cpp.o

.PHONY : src/ui/file.o

# target to build an object file
src/ui/file.cpp.o:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/ui/file.cpp.o
.PHONY : src/ui/file.cpp.o

src/ui/file.i: src/ui/file.cpp.i

.PHONY : src/ui/file.i

# target to preprocess a source file
src/ui/file.cpp.i:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/ui/file.cpp.i
.PHONY : src/ui/file.cpp.i

src/ui/file.s: src/ui/file.cpp.s

.PHONY : src/ui/file.s

# target to generate assembly for a file
src/ui/file.cpp.s:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/ui/file.cpp.s
.PHONY : src/ui/file.cpp.s

src/ui/status.o: src/ui/status.cpp.o

.PHONY : src/ui/status.o

# target to build an object file
src/ui/status.cpp.o:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/ui/status.cpp.o
.PHONY : src/ui/status.cpp.o

src/ui/status.i: src/ui/status.cpp.i

.PHONY : src/ui/status.i

# target to preprocess a source file
src/ui/status.cpp.i:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/ui/status.cpp.i
.PHONY : src/ui/status.cpp.i

src/ui/status.s: src/ui/status.cpp.s

.PHONY : src/ui/status.s

# target to generate assembly for a file
src/ui/status.cpp.s:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/ui/status.cpp.s
.PHONY : src/ui/status.cpp.s

src/ui/ui.o: src/ui/ui.cpp.o

.PHONY : src/ui/ui.o

# target to build an object file
src/ui/ui.cpp.o:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/ui/ui.cpp.o
.PHONY : src/ui/ui.cpp.o

src/ui/ui.i: src/ui/ui.cpp.i

.PHONY : src/ui/ui.i

# target to preprocess a source file
src/ui/ui.cpp.i:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/ui/ui.cpp.i
.PHONY : src/ui/ui.cpp.i

src/ui/ui.s: src/ui/ui.cpp.s

.PHONY : src/ui/ui.s

# target to generate assembly for a file
src/ui/ui.cpp.s:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/ui/ui.cpp.s
.PHONY : src/ui/ui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mouse"
	@echo "... spdlog"
	@echo "... src/log/log.o"
	@echo "... src/log/log.i"
	@echo "... src/log/log.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ui/file.o"
	@echo "... src/ui/file.i"
	@echo "... src/ui/file.s"
	@echo "... src/ui/status.o"
	@echo "... src/ui/status.i"
	@echo "... src/ui/status.s"
	@echo "... src/ui/ui.o"
	@echo "... src/ui/ui.i"
	@echo "... src/ui/ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

